### ISSUE TITLE
Inquiry regarding Lung Organoid Model and RuntimeError during heoca_query.run_scpoli(). 

### ISSUE THREAD

**Issue by jjuhyunkim** [devsystemslab/sc2heoca#1]
Hi developers,

Thank you for providing such valuable resources on GitHub. I'm currently working on lung organoid single-cell data analysis and have found your paper and GitHub page to be extremely helpful references.

However, I have two questions:

Firstly, I noticed that the link to download the lung organoid model seems to be the same as the intestine organoid model (hioca), and I couldn't locate the model for lung organoids on your Zenodo page (8186773). I understand that your paper hasn't been published yet, but if it's possible for you to share the lung organoid model with me, it would be a great opportunity for me.

Secondly, I encountered a RuntimeError during heoca_query.run_scpoli(). 
Here's the detailed error message:

```
Leiden Clustering successful. Found 33 clusters.
 |████████████████████| 100.0%  - val_loss: 406.4587848166 - val_cvae_loss: 406.4587848166 - val_prototype_loss: 0.0000000000 - val_unlabeled_loss: 0.0000000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/User/juhyunk/miniforge3/envs/sc2heoca/lib/python3.9/site-packages/sc2heoca/sc2heoca.py", line 114, in run_scpoli
    results_dict = scpoli_query.classify(adata0.X, adata0.obs["sample_id"].values)
  File "/data/User/juhyunk/miniforge3/envs/sc2heoca/lib/python3.9/site-packages/scarches/models/scpoli/scpoli_model.py", line 389, in classify
    x[batch, :].to(device),
RuntimeError: indices should be either on CPU or on the same device as the indexed tensor (CPU)
```

Could you please provide some setting guidance on how to fix this issue?

Thank you very much!

**Comment by bioqxu** [comment]
Hi, Since we didn't try the model in GPU, could you maybe try to switch to CPU?
For the lung model, we will update the files.

**Comment by fstrijth** [comment]
Hi, I still cannot find the lung organoid model.

**Comment by bioqxu** [comment]
Hi, I’ll upload the model now and let you know once it’s finished.

**Comment by bioqxu** [comment]
The model is uploaded now.
